# plot4.R
oriData <- "./data/household_power_consumption.txt"
oriDataRead <- read.table(oriData,header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
Data <- oriDataRead[oriDataRead$Date %in% c("1/2/2007","2/2/2007") ,]
dateTime <- strptime(paste(Data$Date, Data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
globalActivePower <- as.numeric(Data$Global_active_power)
subMetering1 <- as.numeric(Data$Sub_metering_1)
subMetering2 <- as.numeric(Data$Sub_metering_2)
subMetering3 <- as.numeric(Data$Sub_metering_3)
voltage <- as.numeric(Data$Voltage)
globalReactivePower <- as.numeric(Data$Global_reactive_power)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2)) 
plot(dateTime, globalActivePower, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(dateTime, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(dateTime, subMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(dateTime, subMetering2, type="l", col="red")
lines(dateTime, subMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=, lwd=2.5, col=c("black", "red", "blue"), bty="o")
plot(dateTime, globalReactivePower, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
